"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add apps directory to sys.path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Load environment variables
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-gd=8)9um-*0g%vfzd!26tnon5l)m^di874(6#$m!b9$67n9v!2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*'] # In production, restrict this


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'corsheaders',
    'ninja',
    
    # Internal apps
    'agents.apps.AgentsConfig',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Priority for CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True # Change this for production

# --- CrewAI & LLM Settings ---
LLM_PROVIDER = os.getenv("CREWAI_CONTENT_LLM_PROVIDER", "ollama").strip().lower()
LLM_MODEL = os.getenv("CREWAI_CONTENT_LLM_MODEL", "")
OPENAI_API_KEY = os.getenv("CREWAI_CONTENT_OPENAI_API_KEY", os.getenv("OPENAI_API_KEY"))
OPENAI_BASE_URL = os.getenv("CREWAI_CONTENT_OPENAI_BASE_URL", None)
OLLAMA_BASE_URL = os.getenv("CREWAI_CONTENT_OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("CREWAI_CONTENT_OLLAMA_MODEL", "ollama/llama3.1:8b")
OLLAMA_TEMPERATURE = float(os.getenv("CREWAI_CONTENT_OLLAMA_TEMPERATURE", 0.4))
OLLAMA_TIMEOUT = int(os.getenv("CREWAI_CONTENT_OLLAMA_TIMEOUT", 180))

# Search & Research
MAX_SEARCH_RESULTS = int(os.getenv("CREWAI_CONTENT_MAX_SEARCH_RESULTS", 5))
MAX_SCRAPE_SOURCES = int(os.getenv("CREWAI_CONTENT_MAX_SCRAPE_SOURCES", 4))
MAX_CHARS_PER_SOURCE = int(os.getenv("CREWAI_CONTENT_MAX_CHARS_PER_SOURCE", 6000))
REQUEST_TIMEOUT_SECONDS = int(os.getenv("CREWAI_CONTENT_REQUEST_TIMEOUT", 45))
USER_AGENT = os.getenv("CREWAI_CONTENT_USER_AGENT", "Mozilla/5.0")

# Google CSE
GOOGLE_CSE_API_KEY = os.getenv("GOOGLE_CSE_API_KEY")
GOOGLE_CSE_ID = os.getenv("GOOGLE_CSE_ID")

# MongoDB Fallback (If still used by research scripts)
MONGO_URI = os.getenv("CREWAI_CONTENT_MONGO_URI")
MONGO_DB_NAME = os.getenv("CREWAI_CONTENT_MONGO_DB")
MONGO_OUTPUT_COLL = os.getenv("CREWAI_CONTENT_OUTPUT_COLLECTION", "generated_content_runs")
SAVE_RESULT_DEFAULT = os.getenv("CREWAI_CONTENT_SAVE_RESULT", "True") == "True"
MARK_TOPIC_PROCESSED_DEFAULT = os.getenv("CREWAI_CONTENT_MARK_TOPIC_PROCESSED", "True") == "True"
